version: '2'
services:
  rpi-gpio:
    restart: always
    build: ./rpi-gpio
    privileged: true
  wpe:
    restart: always
    build: ./wpe
    privileged: true
    ports:
      - 8080:8080
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  photos:
    privileged: true
    restart: always
    build: ./photos
    ports:
      - "8888:8888"
  # balena-cam:
    # build: ./balena-cam
    # privileged: true
    # restart: always
    # network_mode: "host"
    # labels:
      # io.balena.features.kernel-modules: '1'