FROM balenalib/%%BALENA_MACHINE_NAME%%-python

#switch on systemd init system in container
ENV INITSYSTEM on

# pip install python deps from requirements.txt
# For caching until requirements.txt changes
COPY . /usr/src/
WORKDIR /usr/src/

RUN pip install -r /usr/src/requirements.txt

CMD ["python", "gpio.py"]